"""
Controlled package integrity verification.

    npm run check:package

00_READ_FIRST.txt §7 preserves the original baseline SHA256SUMS.txt for the 19 physical
controlled deliverables, and 00_ADDITIONAL_SHA256SUMS.txt records the hashes of the cover note,
vendor message, report review and editable derivative. The vendor message asks us to "verify the
original baseline SHA-256 manifest before implementation" and to "confirm receipt and checksum
verification in one response".

This script recomputes every hash and reports the result, so the confirmation we send is a
measured fact rather than an assurance.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PKG = ROOT / "docs" / "ROOTS_AI_RAHUL_M3_FINAL_CORRECTED_VERIFIED_2026-09-24 (3)"
OUT = ROOT / "docs" / "m3" / "ROOTS-AI_M3_Package_Integrity_Verification.md"

MANIFESTS = [
    (PKG / "01_CONTROLLED_BASELINE" / "SHA256SUMS.txt", PKG / "01_CONTROLLED_BASELINE", "Original baseline manifest — 19 controlled deliverables"),
    (PKG / "00_ADDITIONAL_SHA256SUMS.txt", PKG, "Additional manifest — cover note, vendor message, report review, editable derivative"),
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    sections: list[tuple[str, list[tuple[str, str, str]]]] = []
    failures: list[str] = []
    total = ok = 0

    for manifest, base, label in MANIFESTS:
        if not manifest.exists():
            failures.append(f"manifest not found: {manifest.relative_to(ROOT)}")
            continue

        rows: list[tuple[str, str, str]] = []
        for line in manifest.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            expected, _, name = line.partition("  ")
            name = name.strip().lstrip("*")
            if not expected or not name:
                continue
            total += 1
            target = base / name
            if not target.exists():
                rows.append((name, "**FILE MISSING**", expected[:16] + "…"))
                failures.append(f"{name}: listed in the manifest but not present")
                continue
            actual = sha256(target)
            if actual == expected:
                ok += 1
                rows.append((name, "MATCH", expected[:16] + "…"))
            else:
                rows.append((name, "**MISMATCH**", f"expected {expected[:16]}… got {actual[:16]}…"))
                failures.append(f"{name}: hash mismatch")
        sections.append((label, rows))

    lines = [
        "# ROOTS-AI™ — controlled package integrity verification",
        "",
        "**Requested by:** `00_VENDOR_MESSAGE_TO_RAHUL.txt` — \"verify the original baseline SHA-256",
        'manifest before implementation" and "confirm receipt and checksum verification in one',
        'response"; `00_READ_FIRST.txt` §7.',
        "",
        "**Generated by** `npm run check:package`. Every hash below is recomputed from the file on",
        "disk at generation time.",
        "",
        f"## Result: {ok}/{total} files match their recorded SHA-256",
        "",
    ]

    if failures:
        lines += ["**Discrepancies found — see the tables below and the list at the end.**", ""]
    else:
        lines += [
            "Receipt and checksum verification are confirmed. Every controlled deliverable in the",
            "package is byte-identical to the manifest issued with it, so the documents implemented",
            "against are the documents ROOTS sent.",
            "",
        ]

    for label, rows in sections:
        lines += [f"## {label}", "", "| File | Result | SHA-256 |", "|---|---|---|"]
        for name, result, digest in rows:
            lines.append(f"| `{name}` | {result} | `{digest}` |")
        lines.append("")

    lines += [
        "## Precedence",
        "",
        "`00_READ_FIRST.txt` §1 records that the original controlled PDFs govern where a derivative",
        "differs, and §3 that the editable C-07 working copy is not a newly issued controlled",
        "source. Our C-07 completion writes only the three vendor columns and leaves every original",
        "column untouched, so the controlled original continues to govern.",
        "",
    ]

    if failures:
        lines += ["## Discrepancies", "", "```", *failures, "```", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"{ok}/{total} files match their recorded SHA-256")
    if failures:
        print(f"\nFAILED — {len(failures)} discrepancy(ies):", file=sys.stderr)
        for f in failures:
            print("  " + f, file=sys.stderr)
        return 1
    print("\nPASS - receipt and checksum verification confirmed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
