/**
 * Generates the driver state-by-state verification matrix (ROOTS direction D-04, 25 Sep 2026):
 * "a state-by-state verification matrix identifying the controlling source, input condition,
 * canonical output, rendered wording, web result, PDF result, and test reference."
 *
 *     npm run evidence:drivers
 *
 * Every row is produced by running the real engine and the real report builder over the
 * controlled Golden Tests. Nothing is transcribed by hand, so the matrix cannot drift from the
 * implementation it describes.
 *
 * Web and PDF columns: both renderings take `report.sections` from the same stored canonical
 * object — app/report/[id]/page.tsx maps over it, and lib/report/pdf.ts draws the same array.
 * Neither derives drivers of its own, which is why the rendered wording column applies to both.
 * tests/report/driverStates.test.ts asserts that equality rather than assuming it.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { buildReport, driverName, type DeterministicReport } from '../../lib/report/build';
import golden from '../../lib/scoring/c02-golden-tests.json';
import { computeScores, type NormalizedInput, type ScoringResult } from '../../lib/scoring/engine';
import { toScoresRow } from '../../lib/scoring/scoresRow';

const CO_PRIMARY = /^([A-Z]{2})\+([A-Z]{2}) co-primary$/;
const OUT = join(process.cwd(), 'docs', 'm3', 'ROOTS-AI_M3_Driver_State_Matrix.md');

interface Row {
  state: string;
  source: string;
  caseId: string;
  condition: string;
  canonical: string;
  rendered: { summary: string; drivers: string; card: string; triad: string };
  coPrimaryIntact: string;
}

function build(scoring: ScoringResult, id: string): DeterministicReport {
  return buildReport({
    reportId: `RPT-STATE-${id}`,
    generatedAt: '2026-09-25T12:00:00.000Z',
    participantDisplay: null,
    questionnaireVersion: '1.0.1',
    auditTraceReference: `scores/${id}`,
    scoring,
    protective: { P1: true, P2: true, P3: false, P4: false, P5: true },
    answers: {},
  });
}

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
const clip = (s: string, n = 150) => (s.length > n ? `${s.slice(0, n)}…` : s);

function describeState(scoring: ScoringResult): { state: string; source: string } {
  const n = scoring.drivers.length;
  const co = scoring.drivers.some((d) => CO_PRIMARY.test(d));
  if (n === 0) return { state: 'No eligible driver', source: 'C-02 DRV-001 (eligibility ≥ 25); C-03 §4.6 no-dominant-burden copy' };
  if (co) return { state: `Co-primary output (${n} ${n === 1 ? 'entry' : 'entries'})`, source: 'C-02 DRV-004 (co-primary pair reported once); C-03 v1.0.1 §4' };
  return { state: `${n} driver ${n === 1 ? 'entry' : 'entries'}`, source: 'C-02 DRV-002 (ranking), DRV-003 (tie order); C-03 v1.0.1 §4' };
}

const rows: Row[] = [];
const seen = new Set<string>();

for (const c of golden.cases) {
  const scoring = computeScores(c.input as unknown as NormalizedInput);
  const { state, source } = describeState(scoring);

  // One representative case per distinct state, so the matrix stays readable.
  if (seen.has(state)) continue;
  seen.add(state);

  const report = build(scoring, c.test_id);
  const s = (n: number) => report.sections[n - 1].paragraphs.join(' ');
  const triad = (report.sections[7].triad ?? []).map((t) => `${t.kind}: ${t.label}`).join(' · ');

  const coPrimary = scoring.drivers.find((d) => CO_PRIMARY.test(d));
  const row = toScoresRow('00000000-0000-4000-8000-000000000000', scoring, {});

  rows.push({
    state,
    source,
    caseId: c.test_id,
    condition: `Eligible domains ≥ 25: ${Object.entries(scoring.domains)
      .filter(([, v]) => v !== null && (v as number) >= 25)
      .map(([d, v]) => `${d} ${v}`)
      .join(', ') || 'none'}`,
    canonical: JSON.stringify(scoring.drivers),
    rendered: {
      summary: clip(s(2)),
      drivers: clip(s(6)),
      card: clip(report.sections[16].items?.find((i) => i.label === 'Drivers')?.value ?? ''),
      triad: clip(triad),
    },
    coPrimaryIntact: coPrimary
      ? `\`primary_driver\` = \`${row.primary_driver}\` — entry kept whole, not split`
      : 'n/a',
  });
}

const lines: string[] = [
  '# ROOTS-AI™ — M3 driver state verification matrix',
  '',
  '**Direction:** D-04, 25 September 2026 — verify the co-primary correction throughout the report,',
  'and provide a state-by-state matrix.',
  '',
  '**Generated by** `npm run evidence:drivers` from the controlled Golden Tests, the C-02 engine and',
  'the report builder. No row is written by hand.',
  '',
  `**Generated:** ${new Date().toISOString()}`,
  '',
  '## How web and PDF are covered',
  '',
  'Both renderings read `report.sections` from the same stored canonical object:',
  '`app/report/[id]/page.tsx` maps over it and `lib/report/pdf.ts` draws the same array. Neither',
  'derives drivers of its own, so the rendered wording below is what both outputs show.',
  '`tests/report/driverStates.test.ts` asserts that equality rather than assuming it.',
  '',
  '## States',
  '',
];

for (const r of rows) {
  lines.push(
    `### ${r.state}`,
    '',
    `| Field | Value |`,
    `|---|---|`,
    `| Controlling source | ${cell(r.source)} |`,
    `| Input condition | Golden Test \`${r.caseId}\` — ${cell(r.condition)} |`,
    `| Canonical output (C-02) | \`${cell(r.canonical)}\` |`,
    `| Canonical object | \`report.drivers\` identical to the C-02 output |`,
    `| Executive Summary (§2) | ${cell(r.rendered.summary)} |`,
    `| Key Drivers (§6) | ${cell(r.rendered.drivers)} |`,
    `| Biological Card (§17) | ${cell(r.rendered.card)} |`,
    `| Biological Triad (§8) | ${cell(r.rendered.triad)} |`,
    `| Web result | Renders the sections above from the stored canonical object |`,
    `| PDF result | Renders the same sections from the same object |`,
    `| Co-primary structure | ${cell(r.coPrimaryIntact)} |`,
    `| Test reference | \`tests/report/driverStates.test.ts\` |`,
    '',
  );
}

lines.push(
  '## What the tests assert',
  '',
  '| Assertion | Test |',
  '|---|---|',
  '| The canonical object carries the C-02 output unchanged | `the canonical object carries the C-02 output unchanged` |',
  '| A co-primary entry is never split, duplicated or re-ranked, in any section, the Triad or the stored score row | `a co-primary entry is never split into two entries, anywhere` |',
  '| Key Drivers ranks exactly the entries C-02 returned, in order | `Key Drivers ranks exactly the entries C-02 returned, in order` |',
  '| The no-driver state uses the approved copy and invents nothing | `no eligible driver renders the approved null copy and invents nothing` |',
  '| No unresolved placeholder survives in any state | `no unresolved placeholder survives in any state` |',
  '| Every driver count C-02 can produce is covered | `every driver state C-02 can produce is covered by these cases` |',
  '| Web and PDF read the same canonical sections | `web and PDF read the same canonical sections (no second driver source)` |',
  '',
  '## Scope',
  '',
  'Nothing in this verification changed C-01, C-02, the deterministic engine, the Golden Test',
  'expected outputs or the canonical null behaviour. The canonical output is read and the',
  'rendering is checked against it.',
  '',
  '## Open',
  '',
  'The driver and Triad wording remains subject to C-03 state and content-rule verification, as',
  'recorded in the decision log. This matrix evidences the structural handling, not approval of',
  'the wording.',
  '',
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`wrote ${OUT}`);
console.log(`${rows.length} distinct driver states from ${golden.cases.length} Golden Tests`);
