/**
 * Report-review point 21 — seven-domain x four-classification content matrix.
 *
 *     npm run evidence:point21
 *
 * ROOTS decision of 29 September 2026, item 6: "Keep point 21 open... Please prepare the
 * proposed seven-domain x four-classification matrix using the existing approved content only.
 * For each combination, include the domain, classification, approved domain meaning, approved
 * classification explanation, exact current rendered text, source references, content
 * identifiers, and any relevant approved material that could support additional interpretation.
 * Mark any missing domain-specific interpretation as requiring ROOTS content approval."
 *
 * And, emphatically: "Do not fill those cells with newly authored physiological or medical
 * claims, and do not generate variations merely to make all 28 cells sound different. The matrix
 * is a review instrument, not an instruction to create 28 new interpretations."
 *
 * This script therefore authors nothing. Every string it prints is read from the controlled
 * content module, and the "current rendered text" column is produced by the real report builder,
 * so what ROOTS reviews is exactly what a participant sees. The interpretation column is left
 * empty and marked as requiring ROOTS approval.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  CLASSIFICATION_EXPLANATIONS,
  DOMAIN_LABELS,
  DOMAIN_MEANINGS,
  DOMAIN_DISPLAY_ORDER,
} from '../../lib/report/c03-content';
import { buildReport } from '../../lib/report/build';
import golden from '../../lib/scoring/c02-golden-tests.json';
import { computeScores, type NormalizedInput } from '../../lib/scoring/engine';

const OUT = join(process.cwd(), 'docs', 'm3', 'ROOTS-AI_M3_Point21_Content_Matrix.md');

/** C-02 Classifications, lowest burden first. Bounds are quoted for traceability. */
const BANDS = [
  { label: 'Optimized', range: '0-24', interpretation: 'Lower reported burden' },
  { label: 'Compensating', range: '25-49', interpretation: 'Signals present; compensation appears active' },
  { label: 'Strained', range: '50-74', interpretation: 'Multiple or frequent signals' },
  {
    label: 'Dysregulated',
    range: '75-100',
    interpretation: 'High reported burden; educational prompt to seek appropriate support',
  },
];

/**
 * The rendered text for a domain at a classification, taken from the real builder rather than
 * assembled here, so the matrix cannot show wording the report does not actually produce.
 */
function renderedSamples(): Map<string, string> {
  const out = new Map<string, string>();
  for (const c of golden.cases) {
    const scoring = computeScores(c.input as unknown as NormalizedInput);
    const report = buildReport({
      reportId: `RPT-P21-${c.test_id}`,
      generatedAt: '2026-09-29T12:00:00.000Z',
      participantDisplay: null,
      questionnaireVersion: '1.0.1',
      auditTraceReference: `scores/${c.test_id}`,
      scoring,
      protective: { P1: true, P2: true, P3: false, P4: false, P5: true },
      answers: {},
    });
    for (const item of report.sections[6].items ?? []) {
      const domain = DOMAIN_DISPLAY_ORDER.find((d) => DOMAIN_LABELS[d] === item.label);
      if (!domain) continue;
      const band = BANDS.find((b) => item.note?.includes(CLASSIFICATION_EXPLANATIONS[b.label]));
      if (!band) continue;
      const key = `${domain}|${band.label}`;
      if (!out.has(key)) out.set(key, item.note ?? '');
    }
  }
  return out;
}

const samples = renderedSamples();

const lines: string[] = [
  '# ROOTS-AI™ — report-review point 21 content matrix',
  '',
  '> **Current status: point 21 is CLOSED for M3.** ROOTS decided on 1 October 2026 that M3 does',
  '> not require 28 new domain × state interpretation paragraphs. Where no controlled',
  '> domain-specific interpretation exists, the existing approved generic classification and state',
  '> content remains, and no replacement clinical interpretation is invented. **This workbook is',
  '> retained as a documented future content-gap inventory, not as an open M3 item.**',
  '',
  '**Originally prepared under the ROOTS decision of 29 September 2026, item 6**, which kept point',
  '21 open at that time. That instruction is superseded by the decision above. This matrix is the',
  'review instrument the decision asks for, prepared "using the existing approved content only".',
  '',
  '**Generated by** `npm run evidence:point21`. Every approved string is read from the controlled',
  'content module, and the rendered-text column is produced by the real report builder, so what is',
  'reviewed below is exactly what a participant sees.',
  '',
  '**Nothing in this document is newly authored.** Per the decision, no cell has been filled with',
  'physiological or medical claims, and no variations have been generated to make the 28',
  'combinations sound different. The interpretation column is deliberately empty.',
  '',
  '**To work in rather than read:** the same 28 rows are in',
  '[`docs/m3/evidence/Point21_Content_Matrix_FOR_ROOTS.xlsx`](evidence/Point21_Content_Matrix_FOR_ROOTS.xlsx),',
  'prepared for the review of 29 September 2026, item 1. Four decision columns are empty and',
  'unlocked \u2014 whether the combination requires additional content, the approved wording, its',
  'content identifier, and notes. Every column carrying controlled content is locked, and the sheet',
  'is protected without a password, so the guard is against a slip rather than against ROOTS.',
  'Build it with `npm run evidence:point21 && npm run evidence:point21-xlsx`; a completed copy',
  'should be returned under a different name, because regenerating overwrites the file.',
  '',
  '## Sources',
  '',
  '| Content | Source | Identifier |',
  '|---|---|---|',
  '| Domain labels and meanings | C-03 §3, approved labels and meanings | `DOMAIN_LABELS`, `DOMAIN_MEANINGS` |',
  '| Classification explanations | C-03 §3, participant-facing explanation of each classification | `CLASSIFICATION_EXPLANATIONS` |',
  '| Classification bounds and approved interpretation | C-02 `Classifications` sheet, scale `DOMAIN` | C-02 v1.0.1 CORRECTED |',
  '| Rendered text | `lib/report/build.ts`, section 7 items | report template v1.0.1 |',
  '',
  '## The four approved classification explanations',
  '',
  'C-03 supplies one explanation per classification. They are keyed to the classification, not to',
  'the domain, which is the mechanism behind the repetition point 21 describes: any two domains',
  'sharing a classification necessarily read identically at this point.',
  '',
  '| Classification | C-02 range | C-02 approved interpretation | C-03 participant-facing explanation |',
  '|---|---|---|---|',
];

for (const b of BANDS) {
  lines.push(`| ${b.label} | ${b.range} | ${b.interpretation} | ${CLASSIFICATION_EXPLANATIONS[b.label]} |`);
}

lines.push(
  '',
  '## The seven approved domain meanings',
  '',
  '| Domain | Label | C-03 approved meaning |',
  '|---|---|---|',
);

for (const d of DOMAIN_DISPLAY_ORDER) {
  lines.push(`| ${d} | ${DOMAIN_LABELS[d]} | ${DOMAIN_MEANINGS[d]} |`);
}

lines.push(
  '',
  '## The 7 x 4 matrix',
  '',
  'One row per combination. The final column is what ROOTS is asked to determine: which',
  'combinations genuinely require additional approved content, and which are adequately served by',
  'the existing pairing.',
  '',
  '| # | Domain | Classification | Approved domain meaning | Approved classification explanation | Domain-specific interpretation |',
  '|---|---|---|---|---|---|',
);

let n = 0;
const missing: string[] = [];
for (const d of DOMAIN_DISPLAY_ORDER) {
  for (const b of BANDS) {
    n += 1;
    missing.push(`${d} x ${b.label}`);
    lines.push(
      `| ${n} | ${DOMAIN_LABELS[d]} | ${b.label} | ${DOMAIN_MEANINGS[d]} | ${CLASSIFICATION_EXPLANATIONS[b.label]} | ` +
        '*(none in C-03 — requires ROOTS content approval)* |',
    );
  }
}

lines.push(
  '',
  `**${missing.length} of ${missing.length} combinations** have no domain-specific interpretation in`,
  'C-03 v1.0.1. We searched the controlled pack for a domain-specific interpretation library and',
  'found none: C-03 provides the per-domain meanings and the four per-classification explanations',
  'above, and nothing that combines the two.',
  '',
  '## Exact current rendered text',
  '',
  'What a participant sees today, for each combination the Golden Tests actually produce. Rows',
  'marked *not produced* are combinations no controlled test case generates, so no rendered sample',
  'exists to show.',
  '',
  '| Domain | Classification | Exact current rendered text |',
  '|---|---|---|',
);

for (const d of DOMAIN_DISPLAY_ORDER) {
  for (const b of BANDS) {
    const sample = samples.get(`${d}|${b.label}`);
    lines.push(`| ${DOMAIN_LABELS[d]} | ${b.label} | ${sample ? sample : '*not produced by any Golden Test*'} |`);
  }
}

lines.push(
  '',
  '## What we are not doing, and why',
  '',
  'Two routes would close point 21, and both are closed to the vendor:',
  '',
  '1. **Authoring the 28 strings ourselves** would mean composing participant-facing interpretive',
  '   language about metabolic, sleep, stress and inflammation signals. That is content authority',
  '   we do not hold, and the decision forbids "newly authored physiological or medical claims".',
  '2. **Generating them** is excluded by review point 21 itself: "Do not solve repetition by',
  '   allowing unrestricted AI rewriting."',
  '',
  'The approved current presentation is therefore retained unchanged. **ROOTS closed point 21 for',
  'M3 on 1 October 2026 on exactly that basis**: the approved generic content remains and nothing',
  'is invented to replace it. The matrix below is retained as a future content-gap inventory.',
  '',
  '## What this inventory records for a future release',
  '',
  '**Nothing is asked of ROOTS for M3.** Should a future release add domain-specific',
  'interpretation, it would be issued as a controlled C-03 content amendment with content',
  'identifiers, permitted conditions and tests. The combinations below are the inventory such a',
  'release would start from.',
  '',
  'Constraints the decision records as remaining in force, which any addition must preserve:',
  '',
  '- the four existing classification explanations and their medical boundaries, unless a',
  '  controlled amendment expressly changes them;',
  '- deterministic classifications — no added content may alter how a score or classification is',
  '  produced;',
  '- non-diagnostic framing and the approved safety guidance.',
  '',
  '**Closure:** point 21 closes after the applicable content is approved, implemented and',
  'verified. Accepting the current presentation instead would require a separate, explicit ROOTS',
  'decision changing the review requirement; the decision of 29 September expressly does not issue',
  'one.',
  '',
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`wrote ${OUT}`);

/*
 * The same matrix as data, so the editable workbook ROOTS asked for (item 1 of the review of
 * 29 September 2026) is built from this one source rather than transcribed from the Markdown.
 * scripts/canonical/point21_workbook.py reads it.
 */
const DATA = join(process.cwd(), 'docs', 'm3', 'evidence', 'point21-matrix.json');
writeFileSync(
  DATA,
  JSON.stringify(
    {
      generated_by: 'npm run evidence:point21',
      report_template_version: '1.0.1',
      bands: BANDS,
      domains: DOMAIN_DISPLAY_ORDER.map((d) => ({ id: d, label: DOMAIN_LABELS[d], meaning: DOMAIN_MEANINGS[d] })),
      classification_explanations: CLASSIFICATION_EXPLANATIONS,
      rows: DOMAIN_DISPLAY_ORDER.flatMap((d, i) =>
        BANDS.map((b, j) => ({
          n: i * BANDS.length + j + 1,
          domain_id: d,
          domain_label: DOMAIN_LABELS[d],
          domain_meaning: DOMAIN_MEANINGS[d],
          classification: b.label,
          range: b.range,
          classification_explanation: CLASSIFICATION_EXPLANATIONS[b.label],
          rendered_text: samples.get(`${d}|${b.label}`) ?? null,
        })),
      ),
    },
    null,
    2,
  ),
  'utf8',
);
console.log(`wrote ${DATA}`);
console.log(`${n} combinations; ${missing.length} marked as requiring ROOTS content approval`);
console.log(`${samples.size} combinations have a rendered sample from the Golden Tests`);
