/**
 * Report-review point 19 — inventory of every participant-entered measurement.
 *
 *     npm run evidence:point19
 *
 * ROOTS review of 29 September 2026, item 2, asks for the input inventory point 19 depends on.
 *
 * Point 19 itself is explicit about the limit of our authority: "This item should only be
 * implemented using controlled validation/plausibility ranges. If such ranges are not currently
 * defined in the baseline, flag this for ROOTS rather than inventing thresholds."
 *
 * So this invents nothing. It reads the controlled C-01 question bank and the C-01 Validation
 * sheet, and reports what each input accepts today, what it preserves, and what it does not yet
 * have. The plausibility column is empty for every input, because C-01 defines no plausibility
 * range for any of them, and the table that would carry them is left for ROOTS to fill.
 *
 * The distinction the document turns on: an **acceptance range** decides whether an answer may be
 * submitted at all, and C-01 defines one for each numeric input. A **plausibility range** sits
 * inside it and decides whether an accepted answer is unusual enough to ask the participant to
 * check. C-01 defines none. The 44 cm waist in the review is the case that shows why the first
 * does not do the work of the second: it is inside the acceptance range, so nothing asks.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { MODULES, QUESTIONS, VALIDATION_RULES, type Question } from '../../lib/assessment/questionBank';
import { validateAnswer } from '../../lib/assessment/validation';

const OUT = join(process.cwd(), 'docs', 'm3', 'ROOTS-AI_M3_Point19_Input_Inventory.md');

/** Question types a participant types a number into, as opposed to choosing from options. */
const TYPED = ['integer', 'decimal', 'decimal_with_unit'] as const;

const typed = QUESTIONS.filter((q) => (TYPED as readonly string[]).includes(q.question_type));
const scales = QUESTIONS.filter((q) => q.question_type === 'integer_scale');
const freeText = QUESTIONS.filter((q) => q.question_type === 'free_text');

const moduleOf = (q: Question) => MODULES.find((m) => m.module_id === q.module_id)?.module_title ?? q.module_id;

const ruleFor = (q: Question) =>
  VALIDATION_RULES.find((r) => r.applies_to === q.question_id || r.applies_to.split('/').includes(q.question_id));

/** How the entered value is stored, read from what the validator actually returns. */
function storage(q: Question): string {
  const sample =
    q.question_type === 'decimal_with_unit'
      ? { value: 44, unit: 'CM' as const }
      : q.question_id === 'Q1'
        ? 40
        : q.question_id === 'Q3'
          ? 170
          : 80;
  const result = validateAnswer(q.question_id, sample);
  if (!result.ok) return `rejected (${result.rule})`;
  const { raw_value, normalized_value } = result.answer;
  const raw = typeof raw_value === 'object' ? JSON.stringify(raw_value) : String(raw_value);
  return `entered \`${raw}\`; canonical \`${String(normalized_value)}\``;
}

/** Whether the review's worked example is accepted today without any prompt. */
function waistProbe(): { accepted: boolean; canonical: string } {
  const result = validateAnswer('Q6', { value: 44, unit: 'CM' });
  return result.ok
    ? { accepted: true, canonical: String(result.answer.normalized_value) }
    : { accepted: false, canonical: '—' };
}

const probe = waistProbe();

const lines: string[] = [
  '# ROOTS-AI™ — report-review point 19: inventory of participant-entered measurements',
  '',
  'Prepared in response to the ROOTS review of 29 September 2026, item 2.',
  '',
  '**Generated by** `npm run evidence:point19`, which reads the controlled C-01 question bank and',
  'Validation sheet. Nothing here is authored, and no threshold is proposed.',
  '',
  '## Why this document exists rather than an implementation',
  '',
  'Review point 19 sets the condition itself: "This item should only be implemented using',
  'controlled validation/plausibility ranges. If such ranges are not currently defined in the',
  'baseline, flag this for ROOTS rather than inventing thresholds."',
  '',
  'They are not defined. C-01 gives an acceptance range for each numeric input and no plausibility',
  'range for any of them. So point 19 stays open, and this is the inventory it is open on.',
  '',
  '## The distinction the point turns on',
  '',
  '| | Acceptance range | Plausibility range |',
  '|---|---|---|',
  '| Decides | Whether the answer may be submitted at all | Whether an accepted answer is unusual enough to ask the participant to check |',
  '| Defined in C-01 | **Yes**, for every numeric input | **No**, for any input |',
  '| Behaviour outside it | Blocked with the approved C-01 error | Would prompt: *"This value appears unusual. Please verify the value and unit."* |',
  '| Participant may proceed anyway | No | **Yes** — point 19 requires that a valid unusual value can be confirmed |',
  '',
  `**The review's own example.** A waist of 44 cm is ${probe.accepted ? 'accepted today' : 'rejected today'}` +
    `${probe.accepted ? `, stored canonically as ${probe.canonical} cm, with nothing asked of the participant` : ''}.`,
  'It sits inside VAL-004\'s 40–200 cm acceptance range, so the acceptance range cannot do the work',
  'of a plausibility range. That is the gap point 19 names, reproduced here from the live validator',
  'rather than asserted \u2014 and pinned by `reviewPoints.test.ts`, *the acceptance range does not do',
  'the work of a plausibility range*, which will fail the day a plausibility layer is added without',
  'this document being updated.',
  '',
  '## 1. Inputs a participant types a number into',
  '',
  'These are the only inputs where a typing slip or a unit confusion can produce a valid-looking',
  'wrong number. Every other question is a choice from approved options, where no such error is',
  'possible.',
  '',
  '| Q | Module | Question | Type | Unit handling | C-01 rule | Acceptance range | Plausibility range | Affects scoring |',
  '|---|---|---|---|---|---|---|---|---|',
];

for (const q of typed) {
  const rule = ruleFor(q);
  const unit =
    q.question_type === 'decimal_with_unit'
      ? 'cm or in, **chosen by the participant** and stored as entered'
      : q.validation.includes('cm')
        ? 'cm, fixed'
        : q.validation.includes('kg')
          ? 'kg, fixed'
          : 'years, fixed';
  lines.push(
    `| \`${q.question_id}\` | ${moduleOf(q)} | ${q.question_text} | ${q.question_type} | ${unit} | ` +
      `${rule ? `\`${rule.rule_id}\`` : '—'} | ${q.validation} | **none defined** | ` +
      `${q.scoring_eligible ? 'Yes' : 'No'} |`,
  );
}

lines.push(
  '',
  '### What each one stores',
  '',
  'Taken from the live validator, so this is what the database actually holds.',
  '',
  '| Q | Stored |',
  '|---|---|',
);
for (const q of typed) lines.push(`| \`${q.question_id}\` | ${storage(q)} |`);

lines.push(
  '',
  '### What an implausible value could and could not affect',
  '',
  `All ${typed.length} typed measurements are **context only** \u2014 C-01 marks none of them`,
  '`scoring_eligible`. An implausible waist, height or weight therefore cannot move a domain score,',
  'the Biological State, the Opportunity Score, Confidence or a driver ranking. It would appear in',
  'the report\'s Participant Answers section, and nowhere else.',
  '',
  'That bounds the risk; it does not close the point. A participant reading back a figure they did',
  'not mean to enter is exactly the transparency problem point 20 exists to protect, and point 19',
  'is how a wrong figure is caught before it gets there. Asserted by `reviewPoints.test.ts` \u2014',
  '*every typed measurement is context only*, which fails if a future C-01 revision makes one of',
  'them a scoring input.',
);

lines.push(
  '',
  '### Bounded numeric inputs, listed for completeness',
  '',
  'These accept a number but only from a fixed short scale, so an implausible value cannot be',
  'entered and no plausibility range is meaningful.',
  '',
  '| Q | Question | Type | Range | C-01 rule |',
  '|---|---|---|---|---|',
);
for (const q of scales) {
  const rule = ruleFor(q);
  lines.push(`| \`${q.question_id}\` | ${q.question_text} | ${q.question_type} | ${q.validation} | ${rule ? `\`${rule.rule_id}\`` : '—'} |`);
}
for (const q of freeText) {
  const rule = ruleFor(q);
  lines.push(`| \`${q.question_id}\` | ${q.question_text} | ${q.question_type} | ${q.validation} | ${rule ? `\`${rule.rule_id}\`` : '—'} |`);
}

lines.push(
  '',
  '## 2. What point 19 already requires and already holds',
  '',
  'Four of the point\'s requirements are about not doing something, and the implementation already',
  'does not do it. These need no ROOTS input and are recorded so that the open part of point 19 is',
  'not mistaken for the whole of it.',
  '',
  '| Point 19 requirement | Status | Where |',
  '|---|---|---|',
  '| "must never silently convert, correct or reinterpret participant-entered measurements" | **Held.** The entered number and unit are stored as given; the canonical value is stored beside it, never instead of it. | `reviewPoints.test.ts` — *the entered value and unit are stored as given* |',
  '| "Store and display units explicitly" | **Held.** The unit is stored with the value and printed with it in the report\'s Participant Answers section, in both web and PDF. | `reviewPoints.test.ts` — *the report prints the entered value with its unit* |',
  '| "Never automatically infer cm vs inches, kg vs lb" | **Held.** The participant chooses the unit for waist; every other measurement has one fixed unit and no alternative is accepted. There is no inference anywhere. | `reviewPoints.test.ts` — *a unit is never inferred* |',
  '| "or alter the original response" | **Held.** Answers are shown exactly as submitted (review point 20), and the report carries the entered value, not the converted one. | `reviewPoints.test.ts` |',
  '',
  '## 3. What remains, and what ROOTS would need to supply',
  '',
  'One requirement is outstanding: the verify prompt itself, and the ranges that decide when it',
  'appears. The wording is already issued — "This value appears unusual. Please verify the value',
  'and unit." — so what is missing is only the numbers.',
  '',
  '**For ROOTS to complete.** A plausibility range for each input below: a low and a high bound,',
  'inside the acceptance range, outside which the participant is asked to check. Left empty.',
  '',
  '| Q | Input | Unit | Acceptance range (C-01, unchanged) | Plausible low | Plausible high | ROOTS notes |',
  '|---|---|---|---|---|---|---|',
);

for (const q of typed) {
  const unit = q.question_type === 'decimal_with_unit' ? 'cm (after conversion)' : q.validation.includes('cm') ? 'cm' : q.validation.includes('kg') ? 'kg' : 'years';
  lines.push(`| \`${q.question_id}\` | ${q.question_text} | ${unit} | ${q.validation} | | | |`);
}

lines.push(
  '',
  '### Three questions the ranges do not answer',
  '',
  '1. **Does the prompt block submission or only interrupt it?** Point 19 requires that "the',
  '   participant must remain able to confirm a valid unusual value", so the prompt cannot be a',
  '   block. We read that as: shown before final submission, dismissible by confirming, and the',
  '   answer stored unchanged either way. Confirmation requested.',
  '2. **Is the confirmation recorded?** A participant who confirms an unusual value has made a',
  '   statement about their own data. We would record that confirmation in the audit trail and not',
  '   in the report, unless ROOTS wants it visible to a reviewer.',
  '3. **VAL-004 already reads as a verify prompt.** Its approved wording is "Please verify the',
  '   waist measurement." but its severity is `Block`, so today it rejects rather than asks. If the',
  '   plausibility layer is added, ROOTS may want to confirm whether VAL-004 keeps blocking outside',
  '   40–200 cm, or becomes the prompt it is worded as.',
  '',
  '## Closure',
  '',
  'Point 19 closes when ROOTS issues the plausibility ranges and the answers above, the prompt is',
  'implemented against them, and a test proves that an in-range value is silent, an out-of-range',
  'value asks, and a confirmed unusual value is stored exactly as entered. Until then it stays open',
  'in the 35-point checklist, with this inventory as the dependency.',
  '',
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(`wrote ${OUT}`);
console.log(`${typed.length} typed measurements; ${scales.length + freeText.length} bounded inputs listed for completeness`);
console.log(`plausibility ranges defined in C-01: 0 — the table is left for ROOTS`);
console.log(`waist 44 cm accepted today: ${probe.accepted}`);
