/**
 * C-01 Canonical Question Bank (ROOTS-C01-QBANK-001), loaded verbatim from
 * c01-question-bank.json — generated by scripts/canonical/generate.py from the controlled
 * workbook 02_ROOTS_AI_C01_Canonical_Question_Bank_v1.0.1_CORRECTED.xlsx (DATASET_SOURCE holds
 * its name, version and SHA-256). Question IDs, order, text, options and required / N/A rules
 * come only from that file; nothing here renumbers or rewrites them.
 */

import bank from './c01-question-bank.json';

export type QuestionType =
  | 'integer'
  | 'decimal'
  | 'decimal_with_unit'
  | 'single_select'
  | 'likert'
  | 'multi_select'
  | 'integer_scale'
  | 'free_text';

export interface Option {
  option_order: number;
  option_id: string;
  display_label: string;
  stored_value: number | null;
  is_na: boolean;
}

export interface Question {
  question_id: string;
  question_order: number;
  module_id: string;
  question_text: string;
  question_type: QuestionType;
  option_set_id: string | null;
  required: boolean;
  allow_na: boolean;
  validation: string;
  scoring_eligible: boolean;
  conditional_logic: 'NONE';
  help_text: string | null;
  status: 'APPROVED';
}

export interface Module {
  module_id: string;
  module_order: number;
  module_title: string;
  purpose: string;
  question_range: string;
}

export const QUESTIONNAIRE_VERSION = bank.questionnaire_version;
export const DATASET_ID = bank.dataset_id;
export const DATASET_SOURCE = bank.source;

export const MODULES: readonly Module[] = bank.modules;
export const QUESTIONS: readonly Question[] = bank.questions as Question[];
export const OPTION_SETS: Readonly<Record<string, Option[]>> = bank.option_sets;

export interface ValidationRule {
  rule_id: string;
  applies_to: string;
  rule: string;
  approved_error_or_behavior: string;
  severity: string;
}
export const VALIDATION_RULES: readonly ValidationRule[] = bank.validation_rules as ValidationRule[];

const questionsById = new Map(QUESTIONS.map((q) => [q.question_id, q]));

export function getQuestion(questionId: string): Question | undefined {
  return questionsById.get(questionId);
}

/** Module by 1-based order (the C-05 route segment /module/[1..13]). */
export function getModuleByOrder(order: number): Module | undefined {
  return MODULES.find((m) => m.module_order === order);
}

export function getModuleQuestions(moduleId: string): Question[] {
  return QUESTIONS.filter((q) => q.module_id === moduleId);
}

export function getOptions(question: Question): Option[] {
  return question.option_set_id ? OPTION_SETS[question.option_set_id] ?? [] : [];
}

/**
 * Whether the participant can choose N/A for a question. For option-based questions N/A is
 * the option set's is_na option, so it exists only where the set supplies one (see
 * docs/m1/CLARIFICATIONS.md CL-01 for Q56). For numeric / free-text questions with allow_na it
 * is a separate "Not applicable" control.
 */
export function naOption(question: Question): Option | undefined {
  if (!question.allow_na) return undefined;
  return getOptions(question).find((o) => o.is_na);
}

export function offersSeparateNa(question: Question): boolean {
  return question.allow_na && question.option_set_id === null;
}

/**
 * C-01 help_text entries that describe scoring behaviour for the implementation team rather
 * than guidance for the participant. They stay in the dataset verbatim but are not displayed;
 * ROOTS confirmation is requested in docs/m1/CLARIFICATIONS.md CL-02.
 */
const SCORING_NOTE_HELP = new Set(['Protective wording; reverse-scored.', 'Used only as a protective factor.']);

export function participantHelpText(question: Question): string | null {
  return question.help_text && !SCORING_NOTE_HELP.has(question.help_text) ? question.help_text : null;
}
